### ISSUE TITLE
nick work

### ISSUE THREAD

**Issue by yifan18** [kruvcraft21/GGIl2cpp#1]
I'd like to give it a try, but how could i find the classname or function name in libil2cpp?

i have an app and i can't just use Il2CppDumper to output the c++ files.

**Comment by kruvcraft21** [comment]
you can just leave the offset of the method or its address in memory in the "Il2cpp.FindMethods" function.

**Comment by kruvcraft21** [comment]
I don't see my script as a "dumper", I see it more as a help so that developers of other scripts don't constantly update their scripts related to il2cpp

**Comment by kruvcraft21** [comment]
you can just leave the offset of the method or its address in memory in the "Il2cpp.FindMethods" function. I don't see my script as a "dumper", I see it more as a help so that developers of other scripts don't constantly update their scripts related to il2cpp
