### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by Kosovari2019** [kruvcraft21/GGIl2cpp#2]
64bit is not working for me

**Comment by Kosovari2019** [comment]
![Screenshot_20220709-184510](https://user-images.githubusercontent.com/107588112/178115165-d63cbe51-4154-4e47-bf8e-e2bc21b408f5.png)

**Comment by kruvcraft21** [comment]
can you describe the situation in more detail?

**Comment by kruvcraft21** [comment]
can you describe the situation in more detail?

**Comment by kruvcraft21** [comment]
@Kosovari2019  can you describe the situation in more detail?nothing is clear to me from your screenshot

**Comment by Kosovari2019** [comment]
no matter how many times I search, they don't find anything and the script ends

**Comment by kruvcraft21** [comment]
@Kosovari2019, I asked for more details, but you didn't provide anything ... provide the script you are running, the gameguardian you are using, the script logs, at least something useful.
