### ISSUE TITLE
help

### ISSUE THREAD

**Issue by mslqsis** [kruvcraft21/GGIl2cpp#3]
Excuse me, how to enter any address to get the class and so on?

**Comment by kruvcraft21** [comment]
@mslqsis , 
```Lua
Il2cpp.FindClass({{Class = 0x111111, FieldsDump = true, MethodsDump = true}})
```

**Comment by mslqsis** [comment]
> @mslqsis,
> 
> ```lua
> Il2cpp.FindClass({{Class = 0x111111, FieldsDump = true, MethodsDump = true}})
> ```
Thank you

**Comment by mslqsis** [comment]
> > @mslqsis,
> > ```lua
> > Il2cpp.FindClass({{Class = 0x111111, FieldsDump = true, MethodsDump = true}})
> > ```
> 
> 谢谢你！

It seems that you can only input the address of the class but not the target address to get the class.
My idea is that, for example, an address with gold coins can be used to get its classes, fields and so on.

**Comment by mslqsis** [comment]
I have a source code example as I said above, you can refer to the reference, how to contact you?

**Comment by kruvcraft21** [comment]
@mslqsis , I have indicated my telegram channel in my account profile, there you can find links to my personal account

**Comment by mslqsis** [comment]
@kruvcraft21 Have you received the email I sent you?

**Comment by kruvcraft21** [comment]
@mslqsis , yeap , kruvcraft@yandex.ru

**Comment by kruvcraft21** [comment]
@mslqsis , No , I 'll try to look again , but I don 't think I 've seen anything like this

**Comment by mslqsis** [comment]
@kruvcraft21 You can search for Badcase on githubUse his plugin_bc_class _ field _ search.lua

**Comment by kruvcraft21** [comment]
@mslqsis . as I understood the Badcase code is only suitable for armv7 , I'm not sure if it will suit me

**Comment by mslqsis** [comment]
@kruvcraft21 Your script in the 64-bit offset can be directly into the same, I have tried.

**Comment by mslqsis** [comment]
@kruvcraft21 I've added your personal account at Telegram

**Comment by kruvcraft21** [comment]
@mslqsis , as I understood the Badcase code is only suitable for armv7 , I'm not sure if it will suit me

**Comment by kruvcraft21** [comment]
@mslqsis . it is necessary to think over the appeal to the module and somehow adapt this appeal to the "tagged pointer". I think it will take time

**Comment by mslqsis** [comment]
@kruvcraft21 But do you know how to get the enumeration name and the value it is equal to?
I saw that FindClass can identify the enum, but it can only output the name, not the value it is equal to.

**Comment by kruvcraft21** [comment]
@mslqsis , yeah, I'm working on it at the moment and I'm thinking whether it's worth doing it at all, and output the values of constants. Because the more I do these things, the more my script depends on global-metadata.

**Comment by mslqsis** [comment]
@kruvcraft21 In my mind, this is not what the metadata to take the table to store the need to call very convenient.

**Comment by mslqsis** [comment]
@kruvcraft21 Do you have any ideas for getting classes, fields, etc. From the target address?
Badcase's script is said to be ARM7, but it can be used by changing its offset to arm8.

**Comment by kruvcraft21** [comment]
@mslqsis ,We've discussed everything.  I wrote that it is necessary to think over the function, think over the appeal to it, think over what to do with the "tagged pointer". Or have you forgotten the messages that are above ?

**Comment by kruvcraft21** [comment]
At the moment I am getting constants, because it was in the plans, after the completion of the work, maybe I will start working on what you wrote.
