### ISSUE TITLE
Full dump.cs

### ISSUE THREAD

**Issue by ghost** [kruvcraft21/GGIl2cpp#4]
Is it possible to generate full dump using GG, like Zygisk-Il2CppDumper does? I wanted to dump protected game but it crashes with zygisk module, Perfare has yet to respond. I don't care if the GG process is really slow

**Comment by kruvcraft21** [comment]
@VanHoevenTR . there is no full dump, you will get only those types that have been initialized. At the moment I have only seen such an implementation

**Comment by ghost** [comment]
Initialized types will be ok. At least I will get something to search for

**Comment by kruvcraft21** [comment]
@VanHoevenTR , I'm not even going to position my script as a dumper yet, since the dump will not be effective, but it seems that badcase is going to implement this mechanics in its script
