### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by FussyCone** [kruvcraft21/GGIl2cpp#5]
Hello, sorry for my misunderstanding, but how do you use this script "Il2cppApi.1.6.0.lua"? I run this script and it stops. Do I have to implement my script on top of this one? Can you give an example of a game script to show how to use this plugin?

**Comment by kruvcraft21** [comment]
@FussyCone, https://github.com/kruvcraft21/GGIl2cpp#how-to-use or https://github.com/kruvcraft21/GGIl2cpp/blob/master/test/README.md. You should just require my module and use the functions from it in your script.
