### ISSUE TITLE
Field not found

### ISSUE THREAD

**Issue by SKININ** [kruvcraft21/GGIl2cpp#6]
Hello, I tried to use your Il2cppApi tool to query fields in the game named Arkights. Many different fields were queried, but none of them could be found

**Comment by kruvcraft21** [comment]
@SKININ, provide more information. If possible, then provide the code that was used to search for fields.

**Comment by SKININ** [comment]
I try to search for "m_width" and "atk" fields in the game, but the search fails. The field is not initialized is displayed

**Comment by kruvcraft21** [comment]
@SKININ, are you sure that these fields are really present in the game ?

**Comment by kruvcraft21** [comment]
@SKININ, In this game IL2cpp is rewritten. You will have to search for some constants that the script uses yourself.

I found some. That's how it should work:
```Lua
Il2cppApi[24].ClassApiCountFields = 0xf8
Il2cppApi[24].ClassApiFieldsLink = 0x68
Il2cppApi[24].ClassApiCountMethods = 0xf4
Il2cppApi[24].ClassApiMethodsLink = 0x80
Il2cpp()

print(Il2cpp.FindFields({"atk", "m_width"}))

```

**Comment by SKININ** [comment]
I see Thank you！
